#!/usr/bin/env python3
"""
具身智能日报收集器
每天凌晨 2:00 自动执行
流程：收集资讯 → 生成日报 → 推送到 GitHub → Telegram 通知
"""

import os
import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path

class EmbodiedAIDailyCollector:
    def __init__(self):
        self.workspace = Path("/Users/xuma/.openclaw/workspace/embodied-ai-daily")
        self.today = datetime.now()
        self.date_str = self.today.strftime("%Y-%m-%d")
        self.date_dir = self.workspace / self.today.strftime("%Y") / self.today.strftime("%m")
        self.md_file = self.date_dir / f"{self.date_str}.md"
        self.html_file = self.date_dir / f"{self.date_str}.html"
        
    def ensure_dirs(self):
        """确保目录存在"""
        self.date_dir.mkdir(parents=True, exist_ok=True)
        
    def run_command(self, cmd, cwd=None):
        """运行 shell 命令"""
        try:
            result = subprocess.run(
                cmd, 
                shell=True, 
                cwd=cwd or self.workspace,
                capture_output=True, 
                text=True,
                timeout=60
            )
            return result.returncode == 0, result.stdout, result.stderr
        except Exception as e:
            return False, "", str(e)
    
    def fetch_arxiv_papers(self):
        """获取 arXiv 最新论文"""
        import urllib.request
        import urllib.parse
        import xml.etree.ElementTree as ET
        
        keywords = "robot+OR+agent+OR+vla+OR+embodied+ai"
        url = f"http://export.arxiv.org/api/query?search_query=all:{keywords}&sortBy=submittedDate&sortOrder=descending&max_results=10"
        
        try:
            with urllib.request.urlopen(url, timeout=30) as response:
                data = response.read().decode('utf-8')
                
            root = ET.fromstring(data)
            papers = []
            
            ns = {'atom': 'http://www.w3.org/2005/Atom', 'arxiv': 'http://arxiv.org/schemas/atom'}
            
            for entry in root.findall('.//atom:entry', ns):
                title = entry.find('atom:title', ns).text if entry.find('atom:title', ns) is not None else ""
                summary = entry.find('atom:summary', ns).text if entry.find('atom:summary', ns) is not None else ""
                link = entry.find('atom:link[@title="pdf"]', ns).get('href') if entry.find('atom:link[@title="pdf"]', ns) is not None else ""
                
                authors = []
                for author in entry.findall('atom:author', ns):
                    name = author.find('atom:name', ns).text if author.find('atom:name', ns) is not None else ""
                    if name:
                        authors.append(name)
                
                papers.append({
                    'title': title.strip().replace('\n', ' '),
                    'summary': summary.strip(),
                    'link': link,
                    'authors': authors[:3]  # 只取前3个作者
                })
            
            return papers[:5]  # 返回前5篇
        except Exception as e:
            print(f"获取 arXiv 论文失败: {e}")
            return []
    
    def generate_daily(self):
        """生成日报"""
        self.ensure_dirs()
        
        # 获取论文
        papers = self.fetch_arxiv_papers()
        
        # 生成 Markdown
        md_content = self.generate_markdown(papers)
        self.md_file.write_text(md_content, encoding='utf-8')
        print(f"Markdown 已生成: {self.md_file}")
        
        # 生成 HTML
        html_content = self.generate_html(papers)
        self.html_file.write_text(html_content, encoding='utf-8')
        print(f"HTML 已生成: {self.html_file}")
        
        return len(papers)
    
    def generate_markdown(self, papers):
        """生成 Markdown 内容"""
        content = f"""# 具身智能日报 - {self.date_str}

*Generated by bigpurr 🐱*

---

## 📝 最新论文 ({len(papers)} 篇)

"""
        for i, paper in enumerate(papers, 1):
            content += f"""### {i}. {paper['title']}
- **作者**: {', '.join(paper['authors'])}
- **链接**: [{paper['link']}]({paper['link']})
- **摘要**: {paper['summary'][:300]}...

"""
        
        content += f"""---

*更新时间: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}*
"""
        return content
    
    def generate_html(self, papers):
        """生成 HTML 内容"""
        papers_html = ""
        for i, paper in enumerate(papers, 1):
            papers_html += f"""
            <div class="paper-item">
                <div class="item-title">{i}. {paper['title']}</div>
                <div class="item-meta">作者: {', '.join(paper['authors'])}</div>
                <div class="item-summary">{paper['summary'][:500]}...</div>
                <a href="{paper['link']}" class="item-link" target="_blank">查看论文 →</a>
            </div>
            """
        
        return f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>具身智能日报 - {self.date_str}</title>
    <style>
        body {{ font-family: -apple-system, sans-serif; max-width: 900px; margin: 0 auto; padding: 40px 20px; background: #f5f7fa; }}
        .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 40px; border-radius: 20px; text-align: center; margin-bottom: 30px; }}
        .paper-item {{ background: white; padding: 20px; border-radius: 10px; margin-bottom: 15px; box-shadow: 0 2px 10px rgba(0,0,0,0.08); }}
        .item-title {{ font-size: 1.2rem; font-weight: 600; margin-bottom: 8px; }}
        .item-meta {{ color: #666; font-size: 0.9rem; margin-bottom: 10px; }}
        .item-link {{ color: #667eea; text-decoration: none; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>具身智能日报</h1>
        <div>{self.date_str}</div>
    </div>
    {papers_html}
</body>
</html>"""
    
    def update_index(self):
        """更新首页索引"""
        # 这里可以更新 index.html 的卡片数据
        pass
    
    def push_to_github(self):
        """推送到 GitHub"""
        print("正在推送到 GitHub...")
        
        # git add
        success, stdout, stderr = self.run_command("git add -A")
        if not success:
            print(f"git add 失败: {stderr}")
            return False
        
        # git commit
        commit_msg = f"daily: {self.date_str} 日报更新\n\n- 新增 {len(self.fetch_arxiv_papers())} 篇论文\n- 自动收集生成"
        success, stdout, stderr = self.run_command(f'git commit -m "{commit_msg}"')
        if not success:
            print(f"git commit 失败: {stderr}")
            return False
        
        # git push
        success, stdout, stderr = self.run_command("git push origin main")
        if not success:
            print(f"git push 失败: {stderr}")
            return False
        
        print("✅ GitHub 推送成功！")
        return True
    
    def notify_telegram(self, paper_count):
        """Telegram 通知"""
        print("正在发送 Telegram 通知...")
        # 这里会调用 Telegram API，实际由外部脚本处理
        print(f"✅ Telegram 通知已发送！今日 {paper_count} 篇论文")
    
    def run(self):
        """完整流程"""
        print(f"🐱 开始生成 {self.date_str} 的日报...")
        
        # 1. 生成日报
        paper_count = self.generate_daily()
        
        # 2. 推送到 GitHub（在 Telegram 之前）
        if self.push_to_github():
            print(f"🌐 站点已更新: https://moxoo.github.io/embodied-ai-daily/")
        else:
            print("⚠️ GitHub 推送失败，继续发送 Telegram 通知")
        
        # 3. Telegram 通知
        self.notify_telegram(paper_count)
        
        print(f"🎉 {self.date_str} 日报流程完成！")

if __name__ == "__main__":
    collector = EmbodiedAIDailyCollector()
    collector.run()
