#!/bin/bash
# Telegram 通知脚本
# 在 GitHub 部署完成后调用

DATE=$(date +%Y-%m-%d)
DATE_PATH=$(date +%Y/%m/$DATE.html)

curl -s -X POST \
    "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
    -d "chat_id=8775650500" \
    -d "text=🐱 具身智能日报 - $DATE

✅ 自动部署完成！

📊 今日内容：
• 📝 arXiv 论文已更新
• 🌐 GitHub.io 已部署

🔗 在线查看：
• 首页: https://moxoo.github.io/embodied-ai-daily/
• 今日: https://moxoo.github.io/embodied-ai-daily/$DATE_PATH

---
Generated by bigpurr 🐱" \
    -d "parse_mode=HTML"

echo "Telegram 通知已发送"
